# Shared application properties across all microservices
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

# JWT Global Secret and Expiry Configuration
jwt.secret=${JWT_SECRET:myVeryStrongSecretKeyForJwtAuthentication123456789}
jwt.expiration=3600000
