# MongoDB Connection parameters
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://JananiSivasankar:Janani2407@cluster0.rqcvycq.mongodb.net/ecommerceDB?retryWrites=true&w=majority&appName=Cluster0}

logging.level.com.example.cart_service=DEBUG
