# MongoDB Connection parameters
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://JananiSivasankar:Janani2407@cluster0.rqcvycq.mongodb.net/ecommerceDB?retryWrites=true&w=majority&appName=Cluster0}

# MySQL configurations (for JPA entities/repositories if any shared)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/EcommerceDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.com.example.product_service=DEBUG
